name: Android Build job

on:
  workflow_dispatch:
    inputs: {}
  push:
jobs:
  build:
    name: "Build Android"
    runs-on: ryujinx-ubuntu-latest
    permissions:
      contents: write

    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      RYUJINX_BASE_VERSION: "1.1.0"
      RYUJINX_TARGET_RELEASE_CHANNEL_NAME: "moreo"
      RYUJINX_TARGET_RELEASE_CHANNEL_OWNER: "Ryujinx"
      RYUJINX_TARGET_RELEASE_CHANNEL_REPO: "release-channel-moreo"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: '11'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Install Android dependencies
        run: |
          dotnet workload install android
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;30.0.3" "ndk;23.2.8568313"
      - name: Ensure NuGet Source
        uses: fabriciomurta/ensure-nuget-source@v1
      - name: Add Avalonia Nightly source
        run: dotnet nuget add source -n AvaloniaCI https://nuget.avaloniaui.net/repository/avalonia-nightly/index.json
      - name: Clear
        run: dotnet clean && dotnet nuget locals all --clear
      - name: Get version info
        id: version_info
        run: |
          echo "::set-output name=build_version::${{ env.RYUJINX_BASE_VERSION }}-$(git rev-parse --short "${{ github.sha }}")"
          echo "::set-output name=git_short_hash::$(git rev-parse --short "${{ github.sha }}")"
      - name: Configure for release
        run: |
          sed -r --in-place 's/\%\%RYUJINX_BUILD_VERSION\%\%/${{ steps.version_info.outputs.build_version }}/g;' Ryujinx.Common/ReleaseInformations.cs
          sed -r --in-place 's/\%\%RYUJINX_BUILD_GIT_HASH\%\%/${{ steps.version_info.outputs.git_short_hash }}/g;' Ryujinx.Common/ReleaseInformations.cs
          sed -r --in-place 's/\%\%RYUJINX_TARGET_RELEASE_CHANNEL_NAME\%\%/${{ env.RYUJINX_TARGET_RELEASE_CHANNEL_NAME }}/g;' Ryujinx.Common/ReleaseInformations.cs
          sed -r --in-place 's/\%\%RYUJINX_TARGET_RELEASE_CHANNEL_OWNER\%\%/${{ env.RYUJINX_TARGET_RELEASE_CHANNEL_OWNER }}/g;' Ryujinx.Common/ReleaseInformations.cs
          sed -r --in-place 's/\%\%RYUJINX_TARGET_RELEASE_CHANNEL_REPO\%\%/${{ env.RYUJINX_TARGET_RELEASE_CHANNEL_REPO }}/g;' Ryujinx.Common/ReleaseInformations.cs
      - name: Create output dir
        run: "mkdir release_output"
      - name: Publish Android
        run: |
          dotnet restore ./Ryujinx.Rsc/Ryujinx.Rsc.Mobile/Ryujinx.Rsc.Mobile.csproj
          dotnet msbuild ./Ryujinx.Rsc/Ryujinx.Rsc.Mobile/Ryujinx.Rsc.Mobile.csproj /t:PackageForAndroid /p:Configuration=Release /p:OutputPath=$(realpath release_output)/ /p:JavaSdkDirectory="${{ env.JAVA_HOME }}"
      - name: Pushing new release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.version_info.outputs.build_version }}
          commit: ${{ github.sha }}
          artifacts: "release_output/*.apk"
          body: "For more informations about this release please check out the official [Changelog](https://github.com/Ryujinx/Ryujinx/wiki/Changelog)."
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
