name: Perform checks

on:
  pull_request:

permissions:
  pull-requests: write
  checks: write

concurrency:
  group: pr-checks-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - run: dotnet restore

      - name: Run dotnet format
        run: |
          dotnet tool install -g dotnet-format
          dotnet format style --severity info --verify-no-changes --report ./style-report.json
          dotnet format analyzers --severity info --verify-no-changes --report ./analyzers-report.json

      - name: Upload report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-format
          path: ./*-report.json
